namespace InsuranceApp.CarContextMigration
{
    using InsuranceApp.Models;
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<InsuranceApp.DAL.CarContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
            MigrationsDirectory = @"CarContextMigration";
        }

        protected override void Seed(InsuranceApp.DAL.CarContext context)
        {
            var cars = new List<Car>
            {
                new Car{Year=1999, Make="Nissan", Model="Titan"},
                new Car{Year=1999, Make="Hyundai", Model="Santa Fe"},
                new Car{Year=1999, Make="Hyundai", Model="Veracruz"},
                new Car{Year=1999, Make="Hyundai", Model="Tucson"},
                new Car{Year=1999, Make="Hyundai", Model="Accent"},
                new Car{Year=1999, Make="Hyundai", Model="Genesis"},
                new Car{Year=1999, Make="Hyundai", Model="Azera"},
                new Car{Year=1999, Make="Hyundai", Model="Genesis Coupe"},
                new Car{Year=2004, Make="Porsche", Model="911 Carrera"},
                new Car{Year=2004, Make="Porsche", Model="Carrera GT"},
                new Car{Year=2005, Make="Porsche", Model="911 Carrera"},
                new Car{Year=2010, Make="Nissan", Model="370Z"},
                new Car{Year=2010, Make="Nissan", Model="GT-R"},
                new Car{Year=2010, Make="Nissan", Model="Versa"},
                new Car{Year=2010, Make="Nissan", Model="Sentra"},
                new Car{Year=2010, Make="Nissan", Model="Cube"},
                new Car{Year=2010, Make="Nissan", Model="Murano"},
                new Car{Year=2010, Make="Nissan", Model="Maxima"},
                new Car{Year=2010, Make="Porsche", Model="911"},
                new Car{Year=2010, Make="Porsche", Model="Panamera"},
                new Car{Year=2010, Make="Porsche", Model="Cayman"},
                new Car{Year=2010, Make="Porsche", Model="Cayenne"},
                new Car{Year=2010, Make="Porsche", Model="Boxster"},
                new Car{Year=2010, Make="Mercury", Model="Milan"},
                new Car{Year=2010, Make="Mercury", Model="Mariner"},
                new Car{Year=2010, Make="Mercury", Model="Grand Marquis"},
                new Car{Year=2010, Make="Mercury", Model="Mountaineer"},
                new Car{Year=2010, Make="Land Rover", Model="Freelander"},
                new Car{Year=2010, Make="Land Rover", Model="Range Rover Sport"},
                new Car{Year=2010, Make="Land Rover", Model="Discovery"},
                new Car{Year=2010, Make="Land Rover", Model="Range Rover"},
                new Car{Year=2010, Make="Land Rover", Model="LR2"},
                new Car{Year=2010, Make="Land Rover", Model="LR4"},
                new Car{Year=2010, Make="Mazda", Model="CX-9"},
                new Car{Year=2010, Make="Mazda", Model="Mazdaspeed 3"},
                new Car{Year=2010, Make="Mazda", Model="RX-8"},
                new Car{Year=2010, Make="Mazda", Model="CX-7"},
                new Car{Year=2010, Make="Mazda", Model="Tribute"},
                new Car{Year=2010, Make="Mazda", Model="Mazda3"},
                new Car{Year=2010, Make="Mazda", Model="Mazda6"},
                new Car{Year=2010, Make="Mazda", Model="Mazda5"},
                new Car{Year=2010, Make="Mazda", Model="MX-5"},
                new Car{Year=2010, Make="Mazda", Model="Miata MX-5"},
                new Car{Year=2010, Make="Toyota", Model="Tundra"},
                new Car{Year=2010, Make="Toyota", Model="Camry Hybrid"},
                new Car{Year=2010, Make="Toyota", Model="Avalon"},
                new Car{Year=2010, Make="Toyota", Model="Sienna"},
                new Car{Year=2010, Make="Toyota", Model="FJ Cruiser"},
                new Car{Year=2010, Make="Toyota", Model="Matrix"},
                new Car{Year=2010, Make="Toyota", Model="RAV4"},
                new Car{Year=2010, Make="Toyota", Model="Highlander"},
                new Car{Year=2010, Make="Toyota", Model="Yaris"},
                new Car{Year=2010, Make="Toyota", Model="Camry"},
                new Car{Year=2010, Make="Toyota", Model="Venza"},
                new Car{Year=2010, Make="Toyota", Model="Tacoma"},
                new Car{Year=2010, Make="Toyota", Model="Prius"},
                new Car{Year=2010, Make="Toyota", Model="Sequoia"},
                new Car{Year=2010, Make="Toyota", Model="4Runner"},
                new Car{Year=2010, Make="Toyota", Model="Land Cruiser"},
                new Car{Year=2010, Make="Toyota", Model="Corolla"},
                new Car{Year=2010, Make="Toyota", Model="TundraMax"},
                new Car{Year=2010, Make="Kia", Model="Soul"},
                new Car{Year=2010, Make="Kia", Model="Optima"},
                new Car{Year=2010, Make="Kia", Model="Sportage"},
                new Car{Year=2010, Make="Kia", Model="Sedona"},
                new Car{Year=2010, Make="Kia", Model="Forte"},
                new Car{Year=2010, Make="Kia", Model="Rio"},
                new Car{Year=2010, Make="Kia", Model="Rondo"},
                new Car{Year=2010, Make="Infiniti", Model="QX56"},
                new Car{Year=2010, Make="Infiniti", Model="M"},
                new Car{Year=2010, Make="Infiniti", Model="G37"},
                new Car{Year=2010, Make="Infiniti", Model="EX"},
                new Car{Year=2010, Make="Infiniti", Model="FX"},
                new Car{Year=2010, Make="Infiniti", Model="G"},
                new Car{Year=2010, Make="Infiniti", Model="QX"},
                new Car{Year=2010, Make="Chevrolet", Model="Aveo"},
                new Car{Year=2010, Make="Chevrolet", Model="Traverse"},
                new Car{Year=2010, Make="Chevrolet", Model="Equinox"},
                new Car{Year=2010, Make="Chevrolet", Model="Silverado"},
                new Car{Year=2010, Make="Chevrolet", Model="HHR"},
                new Car{Year=2010, Make="Chevrolet", Model="Express"},
                new Car{Year=2010, Make="Chevrolet", Model="Corvette"},
                new Car{Year=2010, Make="Chevrolet", Model="Impala"},
                new Car{Year=2010, Make="Chevrolet", Model="Colorado"},
                new Car{Year=2010, Make="Chevrolet", Model="Suburban"},
                new Car{Year=2010, Make="Chevrolet", Model="Tahoe"},
                new Car{Year=2010, Make="Chevrolet", Model="Avalanche"},
                new Car{Year=2010, Make="Chevrolet", Model="Malibu"},
                new Car{Year=2010, Make="Chevrolet", Model="Camaro"},
                new Car{Year=2010, Make="Chevrolet", Model="Cobalt"},
                new Car{Year=2010, Make="Chevrolet", Model="Express 1500"},
                new Car{Year=2010, Make="Chevrolet", Model="Express 2500"},
                new Car{Year=2010, Make="Chevrolet", Model="Express 3500"},
                new Car{Year=2010, Make="Chevrolet", Model="Silverado 1500"},
                new Car{Year=2010, Make="Chevrolet", Model="Silverado 2500"},
                new Car{Year=2010, Make="Chevrolet", Model="Silverado 3500"},
                new Car{Year=2010, Make="Chevrolet", Model="Suburban 1500"},
                new Car{Year=2010, Make="Chevrolet", Model="Suburban 2500"},
                new Car{Year=2010, Make="Subaru", Model="Impreza"},
                new Car{Year=2010, Make="Subaru", Model="Tribeca"},
                new Car{Year=2010, Make="Subaru", Model="Legacy"},
                new Car{Year=2010, Make="Subaru", Model="Forester"},
                new Car{Year=2010, Make="Subaru", Model="Impreza WRX"},
                new Car{Year=2010, Make="Subaru", Model="Outback"},
                new Car{Year=2010, Make="Maybach", Model="57"},
                new Car{Year=2010, Make="Maybach", Model="62"},
                new Car{Year=2010, Make="Maybach", Model="Landaulet"},
                new Car{Year=2010, Make="Cadillac", Model="Escalade"},
                new Car{Year=2010, Make="Cadillac", Model="SRX"},
                new Car{Year=2010, Make="Cadillac", Model="DTS"},
                new Car{Year=2010, Make="Cadillac", Model="CTS-V"},
                new Car{Year=2010, Make="Cadillac", Model="CTS"},
                new Car{Year=2010, Make="Cadillac", Model="STS"},
                new Car{Year=2010, Make="Cadillac", Model="Escalade ESV"},
                new Car{Year=2010, Make="Cadillac", Model="Escalade EXT"},
                new Car{Year=2010, Make="Audi", Model="Q7"},
                new Car{Year=2010, Make="Audi", Model="Q5"},
                new Car{Year=2010, Make="Audi", Model="S5"},
                new Car{Year=2010, Make="Audi", Model="TT"},
                new Car{Year=2010, Make="Audi", Model="A4"},
                new Car{Year=2010, Make="Audi", Model="A5"},
                new Car{Year=2010, Make="Audi", Model="A8"},
                new Car{Year=2010, Make="Audi", Model="R8"},
                new Car{Year=2010, Make="Audi", Model="S4"},
                new Car{Year=2010, Make="Audi", Model="A6"},
                new Car{Year=2010, Make="Audi", Model="A3"},
                new Car{Year=2010, Make="Audi", Model="S6"},
                new Car{Year=2010, Make="Lincoln", Model="Town Car"},
                new Car{Year=2010, Make="Lincoln", Model="MKX"},
                new Car{Year=2010, Make="Lincoln", Model="Navigator"},
                new Car{Year=2010, Make="Lincoln", Model="MKZ"},
                new Car{Year=2010, Make="Lincoln", Model="MKT"},
                new Car{Year=2010, Make="Lincoln", Model="MKS"},
                new Car{Year=2010, Make="Lincoln", Model="Navigator L"},
                new Car{Year=2010, Make="Rolls-Royce", Model="Phantom"},
                new Car{Year=2010, Make="Rolls-Royce", Model="Ghost"},
                new Car{Year=2010, Make="Ford", Model="Escape"},
                new Car{Year=2010, Make="Ford", Model="Mustang"},
                new Car{Year=2010, Make="Ford", Model="Transit Connect"},
                new Car{Year=2010, Make="Ford", Model="F-Series Super Duty"},
                new Car{Year=2010, Make="Ford", Model="E-Series"},
                new Car{Year=2010, Make="Ford", Model="Focus"},
                new Car{Year=2010, Make="Ford", Model="Explorer"},
                new Car{Year=2010, Make="Ford", Model="Flex"},
                new Car{Year=2010, Make="Ford", Model="Edge"},
                new Car{Year=2010, Make="Ford", Model="F-Series"},
                new Car{Year=2010, Make="Ford", Model="Fusion"},
                new Car{Year=2010, Make="Ford", Model="Crown Victoria"},
                new Car{Year=2010, Make="Ford", Model="Ranger"},
                new Car{Year=2010, Make="Ford", Model="Taurus"},
                new Car{Year=2010, Make="Ford", Model="Expedition"},
                new Car{Year=2010, Make="Ford", Model="E150"},
                new Car{Year=2010, Make="Ford", Model="E250"},
                new Car{Year=2010, Make="Ford", Model="E350"},
                new Car{Year=2010, Make="Ford", Model="Expedition EL"},
                new Car{Year=2010, Make="Ford", Model="Explorer Sport Trac"},
                new Car{Year=2010, Make="Ford", Model="F150"},
                new Car{Year=2010, Make="Ford", Model="F250"},
                new Car{Year=2010, Make="Ford", Model="F350"},
                new Car{Year=2010, Make="Ford", Model="F450"},
                new Car{Year=2010, Make="Dodge", Model="Caravan"},
                new Car{Year=2010, Make="Dodge", Model="Viper"},
                new Car{Year=2010, Make="Dodge", Model="Charger"},
                new Car{Year=2010, Make="Dodge", Model="Journey"},
                new Car{Year=2010, Make="Dodge", Model="Caliber"},
                new Car{Year=2010, Make="Dodge", Model="Ram"},
                new Car{Year=2010, Make="Dodge", Model="Challenger"},
                new Car{Year=2010, Make="Dodge", Model="Nitro"},
                new Car{Year=2010, Make="Dodge", Model="Avenger"},
                new Car{Year=2010, Make="Dodge", Model="Dakota"},
                new Car{Year=2010, Make="Dodge", Model="Grand Caravan"},
                new Car{Year=2010, Make="Dodge", Model="Ram 1500"},
                new Car{Year=2010, Make="Dodge", Model="Ram 2500"},
                new Car{Year=2010, Make="Dodge", Model="Ram 3500"},
                new Car{Year=2010, Make="Lexus", Model="LS"},
                new Car{Year=2010, Make="Lexus", Model="GS"},
                new Car{Year=2010, Make="Lexus", Model="IS"},
                new Car{Year=2010, Make="Lexus", Model="IS-F"},
                new Car{Year=2010, Make="Lexus", Model="LS Hybrid"},
                new Car{Year=2010, Make="Lexus", Model="LX"},
                new Car{Year=2010, Make="Lexus", Model="RX Hybrid"},
                new Car{Year=2010, Make="Lexus", Model="HS"},
                new Car{Year=2010, Make="Lexus", Model="GX"},
                new Car{Year=2010, Make="Lexus", Model="RX"},
                new Car{Year=2010, Make="Lexus", Model="ES"},
                new Car{Year=2010, Make="Lexus", Model="IS F"},
                new Car{Year=2010, Make="Lexus", Model="SC"},
                new Car{Year=2010, Make="Mitsubishi", Model="Lancer Evolution"},
                new Car{Year=2010, Make="Mitsubishi", Model="Eclipse"},
                new Car{Year=2010, Make="Mitsubishi", Model="Lancer"},
                new Car{Year=2010, Make="Mitsubishi", Model="Galant"},
                new Car{Year=2010, Make="Mitsubishi", Model="Endeavor"},
                new Car{Year=2010, Make="Mitsubishi", Model="Outlander"},
                new Car{Year=2010, Make="Ferrari", Model="458 Italia"},
                new Car{Year=2010, Make="Ferrari", Model="California"},
                new Car{Year=2010, Make="Ferrari", Model="612 Scaglietti"},
                new Car{Year=2010, Make="Ferrari", Model="599 GTB Fiorano"},
                new Car{Year=2010, Make="Maserati", Model="Quattroporte"},
                new Car{Year=2010, Make="Maserati", Model="GranTurismo"},
                new Car{Year=2010, Make="Scion", Model="xB"},
                new Car{Year=2010, Make="Scion", Model="tC"},
                new Car{Year=2010, Make="Scion", Model="xD"},
                new Car{Year=2010, Make="Volvo", Model="C30"},
                new Car{Year=2010, Make="Volvo", Model="S40"},
                new Car{Year=2010, Make="Volvo", Model="V50"},
                new Car{Year=2010, Make="Volvo", Model="XC90"},
                new Car{Year=2010, Make="Volvo", Model="S60"},
                new Car{Year=2010, Make="Volvo", Model="C70"},
                new Car{Year=2010, Make="Volvo", Model="XC70"},
                new Car{Year=2010, Make="Volvo", Model="S80"},
                new Car{Year=2010, Make="Volvo", Model="XC60"},
                new Car{Year=2010, Make="Volvo", Model="V70"},
                new Car{Year=2010, Make="Jeep", Model="Grand Cherokee"},
                new Car{Year=2010, Make="Jeep", Model="Commander"},
                new Car{Year=2010, Make="Jeep", Model="Patriot"},
                new Car{Year=2010, Make="Jeep", Model="Compass"},
                new Car{Year=2010, Make="Jeep", Model="Liberty"},
                new Car{Year=2010, Make="Jeep", Model="Wrangler"},
                new Car{Year=2010, Make="Lotus", Model="Exige"},
                new Car{Year=2010, Make="Lotus", Model="Elise"},
                new Car{Year=2010, Make="Lotus", Model="Evora"},
                new Car{Year=2010, Make="Chrysler", Model="300"},
                new Car{Year=2010, Make="Chrysler", Model="Sebring"},
                new Car{Year=2010, Make="Chrysler", Model="Town & Country"},
                new Car{Year=2010, Make="Chrysler", Model="PT Cruiser"},
                new Car{Year=2010, Make="GMC", Model="Savana"},
                new Car{Year=2010, Make="GMC", Model="Sierra"},
                new Car{Year=2010, Make="GMC", Model="Canyon"},
                new Car{Year=2010, Make="GMC", Model="Terrain"},
                new Car{Year=2010, Make="GMC", Model="Yukon"},
                new Car{Year=2010, Make="GMC", Model="Acadia"},
                new Car{Year=2010, Make="GMC", Model="Savana 1500"},
                new Car{Year=2010, Make="GMC", Model="Savana 2500"},
                new Car{Year=2010, Make="GMC", Model="Savana 3500"},
                new Car{Year=2010, Make="GMC", Model="Sierra 1500"},
                new Car{Year=2010, Make="GMC", Model="Sierra 2500"},
                new Car{Year=2010, Make="GMC", Model="Sierra 3500"},
                new Car{Year=2010, Make="GMC", Model="Yukon XL 1500"},
                new Car{Year=2010, Make="GMC", Model="Yukon XL 2500"},
                new Car{Year=2010, Make="Jaguar", Model="XF"},
                new Car{Year=2010, Make="Jaguar", Model="XK"},
                new Car{Year=2010, Make="Jaguar", Model="XJ"},
                new Car{Year=2010, Make="Bentley", Model="Brooklands"},
                new Car{Year=2010, Make="Bentley", Model="Azure"},
                new Car{Year=2010, Make="Bentley", Model="Continental Flying Spur"},
                new Car{Year=2010, Make="Bentley", Model="Continental Super"},
                new Car{Year=2010, Make="Bentley", Model="Continental GT"},
                new Car{Year=2010, Make="Bentley", Model="Continental GTC"},
                new Car{Year=2010, Make="Bentley", Model="Azure T"},
                new Car{Year=2010, Make="Bentley", Model="Continental"},
                new Car{Year=2010, Make="Suzuki", Model="SX4"},
                new Car{Year=2010, Make="Suzuki", Model="Grand Vitara"},
                new Car{Year=2010, Make="Suzuki", Model="Equator"},
                new Car{Year=2010, Make="Suzuki", Model="Kizashi"},
                new Car{Year=2010, Make="Saab", Model="9-3"},
                new Car{Year=2010, Make="Saab", Model="9-5"},
                new Car{Year=2010, Make="Buick", Model="Lucerne"},
                new Car{Year=2010, Make="Buick", Model="LaCrosse"},
                new Car{Year=2010, Make="Buick", Model="Enclave"},
                new Car{Year=2010, Make="Lamborghini", Model="Gallardo"},
                new Car{Year=2010, Make="Lamborghini", Model="Murciélago"},
                new Car{Year=2010, Make="MINI", Model="Clubman"},
                new Car{Year=2010, Make="MINI", Model="Cooper"},
                new Car{Year=2010, Make="MINI", Model="Cooper Clubman"},
                new Car{Year=2010, Make="Acura", Model="TL"},
                new Car{Year=2010, Make="Acura", Model="RL"},
                new Car{Year=2010, Make="Acura", Model="ZDX"},
                new Car{Year=2010, Make="Acura", Model="TSX"},
                new Car{Year=2010, Make="Acura", Model="MDX"},
                new Car{Year=2010, Make="Acura", Model="RDX"},
                new Car{Year=2010, Make="Tesla", Model="Roadster"},
                new Car{Year=2010, Make="Smart", Model="Fortwo"},
                new Car{Year=2010, Make="Aptera", Model="Type-1h"},
                new Car{Year=2010, Make="Land Rover", Model="Defender Ice Edition"},
                new Car{Year=2010, Make="HUMMER", Model="H3"},
                new Car{Year=2010, Make="HUMMER", Model="H3T"},
                new Car{Year=2010, Make="Pontiac", Model="G3"},
                new Car{Year=2010, Make="Pontiac", Model="G6"},
                new Car{Year=2010, Make="Pontiac", Model="Vibe"},
                new Car{Year=2010, Make="Saturn", Model="Outlook"},
                new Car{Year=2010, Make="Saturn", Model="VUE"},
                new Car{Year=2011, Make="Ford", Model="Taurus"},
                new Car{Year=2011, Make="Ford", Model="Escape"},
                new Car{Year=2011, Make="Ford", Model="F-Series Super Duty"},
                new Car{Year=2011, Make="Ford", Model="Mustang"},
                new Car{Year=2011, Make="Ford", Model="Fusion"},
                new Car{Year=2011, Make="Ford", Model="E-Series"},
                new Car{Year=2011, Make="Ford", Model="Fiesta"},
                new Car{Year=2011, Make="Ford", Model="Explorer"},
                new Car{Year=2011, Make="Ford", Model="Focus"},
                new Car{Year=2011, Make="Ford", Model="F-Series"},
                new Car{Year=2011, Make="Ford", Model="Ranger"},
                new Car{Year=2011, Make="Ford", Model="Transit Connect"},
                new Car{Year=2011, Make="Ford", Model="Edge"},
                new Car{Year=2011, Make="Ford", Model="Expedition"},
                new Car{Year=2011, Make="Ford", Model="Flex"},
                new Car{Year=2011, Make="Ford", Model="E150"},
                new Car{Year=2011, Make="Ford", Model="E250"},
                new Car{Year=2011, Make="Ford", Model="E350"},
                new Car{Year=2011, Make="Ford", Model="Expedition EL"},
                new Car{Year=2011, Make="Ford", Model="F150"},
                new Car{Year=2011, Make="Ford", Model="F250"},
                new Car{Year=2011, Make="Ford", Model="F350"},
                new Car{Year=2011, Make="Ford", Model="F450"},
                new Car{Year=2011, Make="Ford", Model="Crown Victoria"},
                new Car{Year=2011, Make="Toyota", Model="Yaris"},
                new Car{Year=2011, Make="Toyota", Model="4Runner"},
                new Car{Year=2011, Make="Toyota", Model="Camry"},
                new Car{Year=2011, Make="Toyota", Model="Sequoia"},
                new Car{Year=2011, Make="Toyota", Model="Land Cruiser"},
                new Car{Year=2011, Make="Toyota", Model="Avalon"},
                new Car{Year=2011, Make="Toyota", Model="Matrix"},
                new Car{Year=2011, Make="Toyota", Model="Tacoma"},
                new Car{Year=2011, Make="Toyota", Model="Prius"},
                new Car{Year=2011, Make="Toyota", Model="Highlander"},
                new Car{Year=2011, Make="Toyota", Model="Tundra"},
                new Car{Year=2011, Make="Toyota", Model="FJ Cruiser"},
                new Car{Year=2011, Make="Toyota", Model="RAV4"},
                new Car{Year=2011, Make="Toyota", Model="Corolla"},
                new Car{Year=2011, Make="Toyota", Model="Sienna"},
                new Car{Year=2011, Make="Toyota", Model="Venza"},
                new Car{Year=2011, Make="Toyota", Model="Camry Hybrid"},
                new Car{Year=2011, Make="Toyota", Model="TundraMax"},
                new Car{Year=2011, Make="Jaguar", Model="XJ"},
                new Car{Year=2011, Make="Jaguar", Model="XK"},
                new Car{Year=2011, Make="Jaguar", Model="XF"},
                new Car{Year=2011, Make="Mazda", Model="CX-9"},
                new Car{Year=2011, Make="Mazda", Model="Mazda3"},
                new Car{Year=2011, Make="Mazda", Model="RX-8"},
                new Car{Year=2011, Make="Mazda", Model="Mazda6"},
                new Car{Year=2011, Make="Mazda", Model="Mazdaspeed 3"},
                new Car{Year=2011, Make="Mazda", Model="Mazda2"},
                new Car{Year=2011, Make="Mazda", Model="MX-5"},
                new Car{Year=2011, Make="Mazda", Model="Tribute"},
                new Car{Year=2011, Make="Mazda", Model="CX-7"},
                new Car{Year=2011, Make="Mazda", Model="Miata MX-5"},
                new Car{Year=2011, Make="Mercedes-Benz", Model="GLK-Class"},
                new Car{Year=2011, Make="Mercedes-Benz", Model="S-Class"},
                new Car{Year=2011, Make="Mercedes-Benz", Model="CLS-Class"},
                new Car{Year=2011, Make="Mercedes-Benz", Model="SLK-Class"},
                new Car{Year=2011, Make="Mercedes-Benz", Model="E-Class"},
                new Car{Year=2011, Make="Mercedes-Benz", Model="GL-Class"},
                new Car{Year=2011, Make="Mercedes-Benz", Model="C-Class"},
                new Car{Year=2011, Make="Mercedes-Benz", Model="G-Class"},
                new Car{Year=2011, Make="Mercedes-Benz", Model="CL-Class"},
                new Car{Year=2011, Make="Mercedes-Benz", Model="SLS AMG"},
                new Car{Year=2011, Make="Mercedes-Benz", Model="R-Class"},
                new Car{Year=2011, Make="Mercedes-Benz", Model="Sprinter"},
                new Car{Year=2011, Make="Mercedes-Benz", Model="M-Class"},
                new Car{Year=2011, Make="Mercedes-Benz", Model="SL-Class"},
                new Car{Year=2011, Make="Mercedes-Benz", Model="SLS-Class"},
                new Car{Year=2011, Make="Mercedes-Benz", Model="Sprinter 2500"},
                new Car{Year=2011, Make="Mercedes-Benz", Model="Sprinter 3500"},
                new Car{Year=2011, Make="Audi", Model="S6"},
                new Car{Year=2011, Make="Audi", Model="S5"},
                new Car{Year=2011, Make="Audi", Model="Q5"},
                new Car{Year=2011, Make="Audi", Model="A6"},
                new Car{Year=2011, Make="Audi", Model="TT"},
                new Car{Year=2011, Make="Audi", Model="A4"},
                new Car{Year=2011, Make="Audi", Model="A5"},
                new Car{Year=2011, Make="Audi", Model="R8"},
                new Car{Year=2011, Make="Audi", Model="A8"},
                new Car{Year=2011, Make="Audi", Model="A3"},
                new Car{Year=2011, Make="Audi", Model="Q7"},
                new Car{Year=2011, Make="Audi", Model="S4"},
                new Car{Year=2011, Make="Honda", Model="Accord"},
                new Car{Year=2011, Make="Honda", Model="Odyssey"},
                new Car{Year=2011, Make="Honda", Model="Civic"},
                new Car{Year=2011, Make="Honda", Model="Pilot"},
                new Car{Year=2011, Make="Honda", Model="Element"},
                new Car{Year=2011, Make="Honda", Model="Fit"},
                new Car{Year=2011, Make="Honda", Model="CR-Z"},
                new Car{Year=2011, Make="Honda", Model="Ridgeline"},
                new Car{Year=2011, Make="Honda", Model="CR-V"},
                new Car{Year=2011, Make="Honda", Model="Insight"},
                new Car{Year=2011, Make="Honda", Model="Accord Crosstour"},
                new Car{Year=2011, Make="Jeep", Model="Patriot"},
                new Car{Year=2011, Make="Jeep", Model="Grand Cherokee"},
                new Car{Year=2011, Make="Jeep", Model="Liberty"},
                new Car{Year=2011, Make="Jeep", Model="Wrangler"},
                new Car{Year=2011, Make="Jeep", Model="Compass"},
                new Car{Year=2011, Make="BMW", Model="1 Series"},
                new Car{Year=2011, Make="BMW", Model="3 Series"},
                new Car{Year=2011, Make="BMW", Model="5 Series"},
                new Car{Year=2011, Make="BMW", Model="7 Series"},
                new Car{Year=2011, Make="BMW", Model="X6"},
                new Car{Year=2011, Make="BMW", Model="M3"},
                new Car{Year=2011, Make="BMW", Model="X3"},
                new Car{Year=2011, Make="BMW", Model="X5"},
                new Car{Year=2011, Make="BMW", Model="Z4"},
                new Car{Year=2011, Make="BMW", Model="X5 M"},
                new Car{Year=2011, Make="BMW", Model="X6 M"},
                new Car{Year=2011, Make="Dodge", Model="Challenger"},
                new Car{Year=2011, Make="Dodge", Model="Ram"},
                new Car{Year=2011, Make="Dodge", Model="Journey"},
                new Car{Year=2011, Make="Dodge", Model="Avenger"},
                new Car{Year=2011, Make="Dodge", Model="Durango"},
                new Car{Year=2011, Make="Dodge", Model="Dakota"},
                new Car{Year=2011, Make="Dodge", Model="Caliber"},
                new Car{Year=2011, Make="Dodge", Model="Nitro"},
                new Car{Year=2011, Make="Dodge", Model="Caravan"},
                new Car{Year=2011, Make="Dodge", Model="Charger"},
                new Car{Year=2011, Make="Dodge", Model="Grand Caravan"},
                new Car{Year=2011, Make="Nissan", Model="Pathfinder"},
                new Car{Year=2011, Make="Nissan", Model="Altima"},
                new Car{Year=2011, Make="Nissan", Model="Quest"},
                new Car{Year=2011, Make="Nissan", Model="Cube"},
                new Car{Year=2011, Make="Nissan", Model="Frontier"},
                new Car{Year=2011, Make="Nissan", Model="Sentra"},
                new Car{Year=2011, Make="Nissan", Model="Titan"},
                new Car{Year=2011, Make="Nissan", Model="Maxima"},
                new Car{Year=2011, Make="Nissan", Model="370Z"},
                new Car{Year=2011, Make="Nissan", Model="GT-R"},
                new Car{Year=2011, Make="Nissan", Model="Rogue"},
                new Car{Year=2011, Make="Nissan", Model="Xterra"},
                new Car{Year=2011, Make="Nissan", Model="Leaf"},
                new Car{Year=2011, Make="Nissan", Model="Armada"},
                new Car{Year=2011, Make="Nissan", Model="Versa"},
                new Car{Year=2011, Make="Nissan", Model="JUKE"},
                new Car{Year=2011, Make="Nissan", Model="Murano"},
                new Car{Year=2011, Make="GMC", Model="Sierra"},
                new Car{Year=2011, Make="GMC", Model="Yukon"},
                new Car{Year=2011, Make="GMC", Model="Canyon"},
                new Car{Year=2011, Make="GMC", Model="Savana"},
                new Car{Year=2011, Make="GMC", Model="Acadia"},
                new Car{Year=2011, Make="GMC", Model="Terrain"},
                new Car{Year=2011, Make="GMC", Model="Savana 1500"},
                new Car{Year=2011, Make="GMC", Model="Savana 2500"},
                new Car{Year=2011, Make="GMC", Model="Savana 3500"},
                new Car{Year=2011, Make="GMC", Model="Sierra 1500"},
                new Car{Year=2011, Make="GMC", Model="Sierra 2500"},
                new Car{Year=2011, Make="GMC", Model="Sierra 3500"},
                new Car{Year=2011, Make="GMC", Model="Yukon XL 1500"},
                new Car{Year=2011, Make="GMC", Model="Yukon XL 2500"},
                new Car{Year=2011, Make="MINI", Model="Clubman"},
                new Car{Year=2011, Make="MINI", Model="Countryman"},
                new Car{Year=2011, Make="MINI", Model="Cooper"},
                new Car{Year=2011, Make="MINI", Model="Cooper Clubman"},
                new Car{Year=2011, Make="MINI", Model="Cooper Countryman"},
                new Car{Year=2011, Make="Acura", Model="RDX"},
                new Car{Year=2011, Make="Acura", Model="TSX"},
                new Car{Year=2011, Make="Acura", Model="ZDX"},
                new Car{Year=2011, Make="Acura", Model="RL"},
                new Car{Year=2011, Make="Acura", Model="MDX"},
                new Car{Year=2011, Make="Acura", Model="TL"},
                new Car{Year=2011, Make="Chevrolet", Model="Tahoe"},
                new Car{Year=2011, Make="Chevrolet", Model="Corvette"},
                new Car{Year=2011, Make="Chevrolet", Model="Equinox"},
                new Car{Year=2011, Make="Chevrolet", Model="Suburban"},
                new Car{Year=2011, Make="Chevrolet", Model="Malibu"},
                new Car{Year=2011, Make="Chevrolet", Model="Volt"},
                new Car{Year=2011, Make="Chevrolet", Model="Aveo"},
                new Car{Year=2011, Make="Chevrolet", Model="HHR"},
                new Car{Year=2011, Make="Chevrolet", Model="Cruze"},
                new Car{Year=2011, Make="Chevrolet", Model="Express"},
                new Car{Year=2011, Make="Chevrolet", Model="Camaro"},
                new Car{Year=2011, Make="Chevrolet", Model="Silverado"},
                new Car{Year=2011, Make="Chevrolet", Model="Traverse"},
                new Car{Year=2011, Make="Chevrolet", Model="Colorado"},
                new Car{Year=2011, Make="Chevrolet", Model="Avalanche"},
                new Car{Year=2011, Make="Chevrolet", Model="Impala"},
                new Car{Year=2011, Make="Chevrolet", Model="Express 1500"},
                new Car{Year=2011, Make="Chevrolet", Model="Express 2500"},
                new Car{Year=2011, Make="Chevrolet", Model="Express 3500"},
                new Car{Year=2011, Make="Chevrolet", Model="Silverado 1500"},
                new Car{Year=2011, Make="Chevrolet", Model="Silverado 2500"},
                new Car{Year=2011, Make="Chevrolet", Model="Silverado 3500"},
                new Car{Year=2011, Make="Chevrolet", Model="Suburban 1500"},
                new Car{Year=2011, Make="Chevrolet", Model="Suburban 2500"},
                new Car{Year=2011, Make="Aston Martin", Model="V8 Vantage S"},
                new Car{Year=2011, Make="Aston Martin", Model="V8 Vantage"},
                new Car{Year=2011, Make="Aston Martin", Model="Rapide"},
                new Car{Year=2011, Make="Aston Martin", Model="DBS"},
                new Car{Year=2011, Make="Aston Martin", Model="V12 Vantage"},
                new Car{Year=2011, Make="Aston Martin", Model="Virage"},
                new Car{Year=2011, Make="Aston Martin", Model="DB9"},
                new Car{Year=2011, Make="Aston Martin", Model="Vantage"},
                new Car{Year=2011, Make="Bentley", Model="Mulsanne"},
                new Car{Year=2011, Make="Bentley", Model="Continental Super"},
                new Car{Year=2011, Make="Bentley", Model="Continental GTC"},
                new Car{Year=2011, Make="Bentley", Model="Continental Flying Spur"},
                new Car{Year=2011, Make="Bentley", Model="Continental"},
                new Car{Year=2011, Make="Volkswagen", Model="Touareg"},
                new Car{Year=2011, Make="Volkswagen", Model="Golf"},
                new Car{Year=2011, Make="Volkswagen", Model="Routan"},
                new Car{Year=2011, Make="Volkswagen", Model="CC"},
                new Car{Year=2011, Make="Volkswagen", Model="Jetta"},
                new Car{Year=2011, Make="Volkswagen", Model="GTI"},
                new Car{Year=2011, Make="Volkswagen", Model="Eos"},
                new Car{Year=2011, Make="Volkswagen", Model="Tiguan"},
                new Car{Year=2011, Make="Infiniti", Model="EX"},
                new Car{Year=2011, Make="Infiniti", Model="G25"},
                new Car{Year=2011, Make="Infiniti", Model="G37"},
                new Car{Year=2011, Make="Infiniti", Model="QX56"},
                new Car{Year=2011, Make="Infiniti", Model="FX"},
                new Car{Year=2011, Make="Infiniti", Model="M"},
                new Car{Year=2011, Make="Infiniti", Model="IPL G"},
                new Car{Year=2011, Make="Infiniti", Model="G"},
                new Car{Year=2011, Make="Infiniti", Model="QX"},
                new Car{Year=2011, Make="Subaru", Model="Legacy"},
                new Car{Year=2011, Make="Subaru", Model="Impreza WRX"},
                new Car{Year=2011, Make="Subaru", Model="Impreza"},
                new Car{Year=2011, Make="Subaru", Model="Outback"},
                new Car{Year=2011, Make="Subaru", Model="Tribeca"},
                new Car{Year=2011, Make="Subaru", Model="Forester"},
                new Car{Year=2011, Make="Saab", Model="9-3"},
                new Car{Year=2011, Make="Saab", Model="9-5"},
                new Car{Year=2011, Make="Saab", Model="9-4X"},
                new Car{Year=2011, Make="Porsche", Model="911"},
                new Car{Year=2011, Make="Porsche", Model="Cayenne"},
                new Car{Year=2011, Make="Porsche", Model="Panamera"},
                new Car{Year=2011, Make="Porsche", Model="Boxster"},
                new Car{Year=2011, Make="Porsche", Model="Cayman"},
                new Car{Year=2011, Make="Land Rover", Model="Freelander"},
                new Car{Year=2011, Make="Land Rover", Model="Range Rover Sport"},
                new Car{Year=2011, Make="Land Rover", Model="Range Rover"},
                new Car{Year=2011, Make="Land Rover", Model="Discovery"},
                new Car{Year=2011, Make="Land Rover", Model="LR2"},
                new Car{Year=2011, Make="Land Rover", Model="LR4"},
                new Car{Year=2011, Make="Buick", Model="LaCrosse"},
                new Car{Year=2011, Make="Buick", Model="Regal"},
                new Car{Year=2011, Make="Buick", Model="Lucerne"},
                new Car{Year=2011, Make="Buick", Model="Enclave"},
                new Car{Year=2011, Make="Scion", Model="tC"},
                new Car{Year=2011, Make="Scion", Model="xB"},
                new Car{Year=2011, Make="Scion", Model="xD"},
                new Car{Year=2011, Make="Lotus", Model="Elise"},
                new Car{Year=2011, Make="Lotus", Model="Evora"},
                new Car{Year=2011, Make="Lotus", Model="Exige"},
                new Car{Year=2011, Make="Kia", Model="Optima"},
                new Car{Year=2011, Make="Kia", Model="Forte"},
                new Car{Year=2011, Make="Kia", Model="Rio"},
                new Car{Year=2011, Make="Kia", Model="Sedona"},
                new Car{Year=2011, Make="Kia", Model="Sorento"},
                new Car{Year=2011, Make="Kia", Model="Sportage"},
                new Car{Year=2011, Make="Kia", Model="Soul"},
                new Car{Year=2011, Make="Hyundai", Model="Elantra"},
                new Car{Year=2011, Make="Hyundai", Model="Sonata"},
                new Car{Year=2011, Make="Hyundai", Model="Genesis"},
                new Car{Year=2011, Make="Hyundai", Model="Santa Fe"},
                new Car{Year=2011, Make="Hyundai", Model="Tucson"},
                new Car{Year=2011, Make="Hyundai", Model="Equus"},
                new Car{Year=2011, Make="Hyundai", Model="Veracruz"},
                new Car{Year=2011, Make="Hyundai", Model="Accent"},
                new Car{Year=2011, Make="Hyundai", Model="Azera"},
                new Car{Year=2011, Make="Hyundai", Model="Genesis Coupe"},
                new Car{Year=2011, Make="Suzuki", Model="Grand Vitara"},
                new Car{Year=2011, Make="Suzuki", Model="SX4"},
                new Car{Year=2011, Make="Suzuki", Model="Kizashi"},
                new Car{Year=2011, Make="Suzuki", Model="Equator"},
                new Car{Year=2011, Make="Smart", Model="Fortwo"},
                new Car{Year=2011, Make="Volvo", Model="C30"},
                new Car{Year=2011, Make="Volvo", Model="V50"},
                new Car{Year=2011, Make="Volvo", Model="XC90"},
                new Car{Year=2011, Make="Volvo", Model="S60"},
                new Car{Year=2011, Make="Volvo", Model="XC60"},
                new Car{Year=2011, Make="Volvo", Model="XC70"},
                new Car{Year=2011, Make="Volvo", Model="C70"},
                new Car{Year=2011, Make="Volvo", Model="S80"},
                new Car{Year=2011, Make="Volvo", Model="S40"},
                new Car{Year=2011, Make="Rolls-Royce", Model="Phantom"},
                new Car{Year=2011, Make="Rolls-Royce", Model="Ghost"},
                new Car{Year=2011, Make="Lincoln", Model="Navigator"},
                new Car{Year=2011, Make="Lincoln", Model="MKT"},
                new Car{Year=2011, Make="Lincoln", Model="MKS"},
                new Car{Year=2011, Make="Lincoln", Model="MKZ"},
                new Car{Year=2011, Make="Lincoln", Model="Town Car"},
                new Car{Year=2011, Make="Lincoln", Model="MKX"},
                new Car{Year=2011, Make="Lincoln", Model="Navigator L"},
                new Car{Year=2011, Make="Mitsubishi", Model="Eclipse"},
                new Car{Year=2011, Make="Mitsubishi", Model="Outlander"},
                new Car{Year=2011, Make="Mitsubishi", Model="Endeavor"},
                new Car{Year=2011, Make="Mitsubishi", Model="Lancer"},
                new Car{Year=2011, Make="Mitsubishi", Model="Galant"},
                new Car{Year=2011, Make="Mitsubishi", Model="Lancer Evolution"},
                new Car{Year=2011, Make="Mitsubishi", Model="Outlander Sport"},
                new Car{Year=2011, Make="Mercury", Model="Mariner"},
                new Car{Year=2011, Make="Mercury", Model="Grand Marquis"},
                new Car{Year=2011, Make="Mercury", Model="Milan"},
                new Car{Year=2011, Make="Maserati", Model="GranTurismo"},
                new Car{Year=2011, Make="Maserati", Model="Quattroporte"},
                new Car{Year=2011, Make="Chrysler", Model="200"},
                new Car{Year=2011, Make="Chrysler", Model="300"},
                new Car{Year=2011, Make="Chrysler", Model="Town & Country"},
                new Car{Year=2011, Make="Cadillac", Model="DTS"},
                new Car{Year=2011, Make="Cadillac", Model="CTS-V"},
                new Car{Year=2011, Make="Cadillac", Model="CTS"},
                new Car{Year=2011, Make="Cadillac", Model="STS"},
                new Car{Year=2011, Make="Cadillac", Model="SRX"},
                new Car{Year=2011, Make="Cadillac", Model="Escalade"},
                new Car{Year=2011, Make="Cadillac", Model="Escalade ESV"},
                new Car{Year=2011, Make="Cadillac", Model="Escalade EXT"},
                new Car{Year=2011, Make="Maybach", Model="57"},
                new Car{Year=2011, Make="Maybach", Model="62"},
                new Car{Year=2011, Make="Maybach", Model="Landaulet"},
                new Car{Year=2011, Make="Ferrari", Model="458 Italia"},
                new Car{Year=2011, Make="Bugatti", Model="Veyron"},
                new Car{Year=2011, Make="Lamborghini", Model="Gallardo"},
                new Car{Year=2011, Make="Tesla", Model="Roadster"},
                new Car{Year=2011, Make="Ram", Model="1500"},
                new Car{Year=2011, Make="Ram", Model="2500"},
                new Car{Year=2011, Make="Ram", Model="3500"},
                new Car{Year=2011, Make="Ram", Model="Dakota"},
                new Car{Year=2012, Make="Porsche", Model="911"},
                new Car{Year=2012, Make="Porsche", Model="Cayenne"},
                new Car{Year=2012, Make="Porsche", Model="Panamera"},
                new Car{Year=2012, Make="Porsche", Model="Boxster"},
                new Car{Year=2012, Make="Porsche", Model="Cayman"},
                new Car{Year=2012, Make="Nissan", Model="Altima"},
                new Car{Year=2012, Make="Nissan", Model="370Z"},
                new Car{Year=2012, Make="Nissan", Model="Murano"},
                new Car{Year=2012, Make="Nissan", Model="Armada"},
                new Car{Year=2012, Make="Nissan", Model="Pathfinder"},
                new Car{Year=2012, Make="Nissan", Model="Leaf"},
                new Car{Year=2012, Make="Nissan", Model="Xterra"},
                new Car{Year=2012, Make="Nissan", Model="Titan"},
                new Car{Year=2012, Make="Nissan", Model="JUKE"},
                new Car{Year=2012, Make="Nissan", Model="Rogue"},
                new Car{Year=2012, Make="Nissan", Model="Maxima"},
                new Car{Year=2012, Make="Nissan", Model="Versa"},
                new Car{Year=2012, Make="Nissan", Model="Quest"},
                new Car{Year=2012, Make="Nissan", Model="Sentra"},
                new Car{Year=2012, Make="Nissan", Model="GT-R"},
                new Car{Year=2012, Make="Nissan", Model="cube"},
                new Car{Year=2012, Make="Nissan", Model="Frontier"},
                new Car{Year=2012, Make="Nissan", Model="NV1500"},
                new Car{Year=2012, Make="Nissan", Model="NV2500"},
                new Car{Year=2012, Make="Nissan", Model="NV3500"},
                new Car{Year=2012, Make="Cadillac", Model="CTS"},
                new Car{Year=2012, Make="Cadillac", Model="CTS-V"},
                new Car{Year=2012, Make="Cadillac", Model="Escalade"},
                new Car{Year=2012, Make="Cadillac", Model="SRX"},
                new Car{Year=2012, Make="Cadillac", Model="Escalade ESV"},
                new Car{Year=2012, Make="Cadillac", Model="Escalade EXT"},
                new Car{Year=2012, Make="Audi", Model="A3"},
                new Car{Year=2012, Make="Audi", Model="R8"},
                new Car{Year=2012, Make="Audi", Model="A6"},
                new Car{Year=2012, Make="Audi", Model="Q5"},
                new Car{Year=2012, Make="Audi", Model="A5"},
                new Car{Year=2012, Make="Audi", Model="A8"},
                new Car{Year=2012, Make="Audi", Model="TT"},
                new Car{Year=2012, Make="Audi", Model="A7"},
                new Car{Year=2012, Make="Audi", Model="S5"},
                new Car{Year=2012, Make="Audi", Model="A4"},
                new Car{Year=2012, Make="Audi", Model="Q7"},
                new Car{Year=2012, Make="Audi", Model="S4"},
                new Car{Year=2012, Make="Volkswagen", Model="Jetta"},
                new Car{Year=2012, Make="Volkswagen", Model="Golf"},
                new Car{Year=2012, Make="Volkswagen", Model="Routan"},
                new Car{Year=2012, Make="Volkswagen", Model="Touareg"},
                new Car{Year=2012, Make="Volkswagen", Model="Eos"},
                new Car{Year=2012, Make="Volkswagen", Model="New Beetle"},
                new Car{Year=2012, Make="Volkswagen", Model="Passat"},
                new Car{Year=2012, Make="Volkswagen", Model="Tiguan"},
                new Car{Year=2012, Make="Volkswagen", Model="GTI"},
                new Car{Year=2012, Make="Volkswagen", Model="CC"},
                new Car{Year=2012, Make="Land Rover", Model="Range Rover"},
                new Car{Year=2012, Make="Land Rover", Model="Discovery"},
                new Car{Year=2012, Make="Land Rover", Model="Range Rover Sport"},
                new Car{Year=2012, Make="Land Rover", Model="Range Rover Evoque"},
                new Car{Year=2012, Make="Land Rover", Model="LR2"},
                new Car{Year=2012, Make="Land Rover", Model="LR4"},
                new Car{Year=2012, Make="Honda", Model="Odyssey"},
                new Car{Year=2012, Make="Honda", Model="Accord"},
                new Car{Year=2012, Make="Honda", Model="Civic"},
                new Car{Year=2012, Make="Honda", Model="Ridgeline"},
                new Car{Year=2012, Make="Honda", Model="Fit"},
                new Car{Year=2012, Make="Honda", Model="Insight"},
                new Car{Year=2012, Make="Honda", Model="CR-Z"},
                new Car{Year=2012, Make="Honda", Model="Pilot"},
                new Car{Year=2012, Make="Honda", Model="FCX Clarity"},
                new Car{Year=2012, Make="Honda", Model="Crosstour"},
                new Car{Year=2012, Make="Honda", Model="CR-V"},
                new Car{Year=2012, Make="Hyundai", Model="HED-5"},
                new Car{Year=2012, Make="Hyundai", Model="Genesis"},
                new Car{Year=2012, Make="Hyundai", Model="Accent"},
                new Car{Year=2012, Make="Hyundai", Model="Equus"},
                new Car{Year=2012, Make="Hyundai", Model="Santa Fe"},
                new Car{Year=2012, Make="Hyundai", Model="Elantra"},
                new Car{Year=2012, Make="Hyundai", Model="Veracruz"},
                new Car{Year=2012, Make="Hyundai", Model="Sonata"},
                new Car{Year=2012, Make="Hyundai", Model="Tucson"},
                new Car{Year=2012, Make="Hyundai", Model="Veloster"},
                new Car{Year=2012, Make="Hyundai", Model="Azera"},
                new Car{Year=2012, Make="Ford", Model="Focus"},
                new Car{Year=2012, Make="Ford", Model="Mustang"},
                new Car{Year=2012, Make="Ford", Model="F-Series Super Duty"},
                new Car{Year=2012, Make="Ford", Model="E-Series"},
                new Car{Year=2012, Make="Ford", Model="Transit Connect"},
                new Car{Year=2012, Make="Ford", Model="Flex"},
                new Car{Year=2012, Make="Ford", Model="Escape"},
                new Car{Year=2012, Make="Ford", Model="Fusion"},
                new Car{Year=2012, Make="Ford", Model="Taurus"},
                new Car{Year=2012, Make="Ford", Model="Fiesta"},
                new Car{Year=2012, Make="Ford", Model="Explorer"},
                new Car{Year=2012, Make="Ford", Model="Expedition"},
                new Car{Year=2012, Make="Ford", Model="Edge"},
                new Car{Year=2012, Make="Ford", Model="E150"},
                new Car{Year=2012, Make="Ford", Model="E250"},
                new Car{Year=2012, Make="Ford", Model="E350"},
                new Car{Year=2012, Make="Ford", Model="Expedition EL"},
                new Car{Year=2012, Make="Ford", Model="F150"},
                new Car{Year=2012, Make="Ford", Model="F250"},
                new Car{Year=2012, Make="Ford", Model="F350"},
                new Car{Year=2012, Make="Ford", Model="F450"},
                new Car{Year=2012, Make="GMC", Model="Canyon"},
                new Car{Year=2012, Make="GMC", Model="Yukon"},
                new Car{Year=2012, Make="GMC", Model="Sierra"},
                new Car{Year=2012, Make="GMC", Model="Acadia"},
                new Car{Year=2012, Make="GMC", Model="Terrain"},
                new Car{Year=2012, Make="GMC", Model="Savana"},
                new Car{Year=2012, Make="GMC", Model="Savana 1500"},
                new Car{Year=2012, Make="GMC", Model="Savana 2500"},
                new Car{Year=2012, Make="GMC", Model="Savana 3500"},
                new Car{Year=2012, Make="GMC", Model="Sierra 1500"},
                new Car{Year=2012, Make="GMC", Model="Sierra 2500"},
                new Car{Year=2012, Make="GMC", Model="Sierra 3500"},
                new Car{Year=2012, Make="GMC", Model="Yukon XL 1500"},
                new Car{Year=2012, Make="GMC", Model="Yukon XL 2500"},
                new Car{Year=2012, Make="Saab", Model="9-3"},
                new Car{Year=2012, Make="Volvo", Model="C30"},
                new Car{Year=2012, Make="Volvo", Model="XC70"},
                new Car{Year=2012, Make="Volvo", Model="XC60"},
                new Car{Year=2012, Make="Volvo", Model="XC90"},
                new Car{Year=2012, Make="Volvo", Model="C70"},
                new Car{Year=2012, Make="Volvo", Model="S80"},
                new Car{Year=2012, Make="Volvo", Model="S60"},
                new Car{Year=2012, Make="Chevrolet", Model="Corvette"},
                new Car{Year=2012, Make="Chevrolet", Model="Colorado"},
                new Car{Year=2012, Make="Chevrolet", Model="Volt"},
                new Car{Year=2012, Make="Chevrolet", Model="Express"},
                new Car{Year=2012, Make="Chevrolet", Model="Sonic"},
                new Car{Year=2012, Make="Chevrolet", Model="Camaro"},
                new Car{Year=2012, Make="Chevrolet", Model="Cruze"},
                new Car{Year=2012, Make="Chevrolet", Model="Malibu"},
                new Car{Year=2012, Make="Chevrolet", Model="Traverse"},
                new Car{Year=2012, Make="Chevrolet", Model="Equinox"},
                new Car{Year=2012, Make="Chevrolet", Model="Impala"},
                new Car{Year=2012, Make="Chevrolet", Model="Avalanche"},
                new Car{Year=2012, Make="Chevrolet", Model="Express 1500"},
                new Car{Year=2012, Make="Chevrolet", Model="Express 2500"},
                new Car{Year=2012, Make="Chevrolet", Model="Express 3500"},
                new Car{Year=2012, Make="Chevrolet", Model="Silverado 1500"},
                new Car{Year=2012, Make="Chevrolet", Model="Silverado 2500"},
                new Car{Year=2012, Make="Chevrolet", Model="Silverado 3500"},
                new Car{Year=2012, Make="Chevrolet", Model="Suburban 1500"},
                new Car{Year=2012, Make="Chevrolet", Model="Suburban 2500"},
                new Car{Year=2012, Make="Chevrolet", Model="Tahoe"},
                new Car{Year=2012, Make="MINI", Model="Cooper"},
                new Car{Year=2012, Make="MINI", Model="Countryman"},
                new Car{Year=2012, Make="MINI", Model="Clubman"},
                new Car{Year=2012, Make="MINI", Model="Cooper Clubman"},
                new Car{Year=2012, Make="MINI", Model="Cooper Countryman"},
                new Car{Year=2012, Make="BMW", Model="1 Series"},
                new Car{Year=2012, Make="BMW", Model="3 Series"},
                new Car{Year=2012, Make="BMW", Model="5 Series"},
                new Car{Year=2012, Make="BMW", Model="6 Series"},
                new Car{Year=2012, Make="BMW", Model="7 Series"},
                new Car{Year=2012, Make="BMW", Model="M3"},
                new Car{Year=2012, Make="BMW", Model="X3"},
                new Car{Year=2012, Make="BMW", Model="X5"},
                new Car{Year=2012, Make="BMW", Model="X5 M"},
                new Car{Year=2012, Make="BMW", Model="X6"},
                new Car{Year=2012, Make="BMW", Model="X6 M"},
                new Car{Year=2012, Make="BMW", Model="Z4"},
                new Car{Year=2012, Make="Lincoln", Model="MKX"},
                new Car{Year=2012, Make="Lincoln", Model="Navigator"},
                new Car{Year=2012, Make="Lincoln", Model="MKS"},
                new Car{Year=2012, Make="Lincoln", Model="MKT"},
                new Car{Year=2012, Make="Lincoln", Model="MKZ"},
                new Car{Year=2012, Make="Lincoln", Model="Navigator L"},
                new Car{Year=2012, Make="Toyota", Model="4Runner"},
                new Car{Year=2012, Make="Toyota", Model="Highlander"},
                new Car{Year=2012, Make="Toyota", Model="Yaris"},
                new Car{Year=2012, Make="Toyota", Model="Prius v"},
                new Car{Year=2012, Make="Toyota", Model="FJ Cruiser"},
                new Car{Year=2012, Make="Toyota", Model="Camry Hybrid"},
                new Car{Year=2012, Make="Toyota", Model="Sequoia"},
                new Car{Year=2012, Make="Toyota", Model="RAV4"},
                new Car{Year=2012, Make="Toyota", Model="Sienna"},
                new Car{Year=2012, Make="Toyota", Model="Camry"},
                new Car{Year=2012, Make="Toyota", Model="Prius Plug-in Hybrid"},
                new Car{Year=2012, Make="Toyota", Model="Avalon"},
                new Car{Year=2012, Make="Toyota", Model="Corolla"},
                new Car{Year=2012, Make="Toyota", Model="Matrix"},
                new Car{Year=2012, Make="Toyota", Model="Prius"},
                new Car{Year=2012, Make="Toyota", Model="Prius c"},
                new Car{Year=2012, Make="Toyota", Model="Prius Plug-in"},
                new Car{Year=2012, Make="Toyota", Model="Tacoma"},
                new Car{Year=2012, Make="Toyota", Model="TundraMax"},
                new Car{Year=2012, Make="Toyota", Model="Tundra"},
                new Car{Year=2012, Make="Toyota", Model="Venza"},
                new Car{Year=2012, Make="Acura", Model="ZDX"},
                new Car{Year=2012, Make="Acura", Model="MDX"},
                new Car{Year=2012, Make="Acura", Model="TSX"},
                new Car{Year=2012, Make="Acura", Model="TL"},
                new Car{Year=2012, Make="Acura", Model="RL"},
                new Car{Year=2012, Make="Acura", Model="RDX"},
                new Car{Year=2012, Make="Mercedes-Benz", Model="G-Class"},
                new Car{Year=2012, Make="Mercedes-Benz", Model="CLS-Class"},
                new Car{Year=2012, Make="Mercedes-Benz", Model="GL-Class"},
                new Car{Year=2012, Make="Mercedes-Benz", Model="E-Class"},
                new Car{Year=2012, Make="Mercedes-Benz", Model="GLK-Class"},
                new Car{Year=2012, Make="Mercedes-Benz", Model="SLS AMG"},
                new Car{Year=2012, Make="Mercedes-Benz", Model="S-Class"},
                new Car{Year=2012, Make="Mercedes-Benz", Model="CL-Class"},
                new Car{Year=2012, Make="Mercedes-Benz", Model="C-Class"},
                new Car{Year=2012, Make="Mercedes-Benz", Model="SL-Class"},
                new Car{Year=2012, Make="Mercedes-Benz", Model="M-Class"},
                new Car{Year=2012, Make="Mercedes-Benz", Model="R-Class"},
                new Car{Year=2012, Make="Mercedes-Benz", Model="SLK-Class"},
                new Car{Year=2012, Make="Mercedes-Benz", Model="SLS-Class"},
                new Car{Year=2012, Make="Mercedes-Benz", Model="Sprinter 2500"},
                new Car{Year=2012, Make="Mercedes-Benz", Model="Sprinter 3500"},
                new Car{Year=2012, Make="Infiniti", Model="FX"},
                new Car{Year=2012, Make="Infiniti", Model="M"},
                new Car{Year=2012, Make="Infiniti", Model="G37"},
                new Car{Year=2012, Make="Infiniti", Model="G25"},
                new Car{Year=2012, Make="Infiniti", Model="QX56"},
                new Car{Year=2012, Make="Infiniti", Model="IPL G"},
                new Car{Year=2012, Make="Infiniti", Model="EX"},
                new Car{Year=2012, Make="Infiniti", Model="G"},
                new Car{Year=2012, Make="Infiniti", Model="QX"},
                new Car{Year=2012, Make="Aston Martin", Model="DBS"},
                new Car{Year=2012, Make="Aston Martin", Model="DB9"},
                new Car{Year=2012, Make="Aston Martin", Model="V12 Vantage"},
                new Car{Year=2012, Make="Aston Martin", Model="Virage"},
                new Car{Year=2012, Make="Aston Martin", Model="V8 Vantage"},
                new Car{Year=2012, Make="Aston Martin", Model="Rapide"},
                new Car{Year=2012, Make="Aston Martin", Model="V8 Vantage S"},
                new Car{Year=2012, Make="Lexus", Model="RX"},
                new Car{Year=2012, Make="Lexus", Model="LS"},
                new Car{Year=2012, Make="Lexus", Model="IS"},
                new Car{Year=2012, Make="Lexus", Model="IS-F"},
                new Car{Year=2012, Make="Lexus", Model="CT"},
                new Car{Year=2012, Make="Lexus", Model="RX Hybrid"},
                new Car{Year=2012, Make="Lexus", Model="LS Hybrid"},
                new Car{Year=2012, Make="Lexus", Model="ES"},
                new Car{Year=2012, Make="Lexus", Model="LFA"},
                new Car{Year=2012, Make="Lexus", Model="HS"},
                new Car{Year=2012, Make="Lexus", Model="GX"},
                new Car{Year=2012, Make="FIAT", Model="500"},
                new Car{Year=2012, Make="Fiat", Model="Nuova 500"},
                new Car{Year=2012, Make="Dodge", Model="Avenger"},
                new Car{Year=2012, Make="Dodge", Model="Caravan"},
                new Car{Year=2012, Make="Dodge", Model="Charger"},
                new Car{Year=2012, Make="Dodge", Model="Challenger"},
                new Car{Year=2012, Make="Dodge", Model="Caliber"},
                new Car{Year=2012, Make="Dodge", Model="Durango"},
                new Car{Year=2012, Make="Dodge", Model="Journey"},
                new Car{Year=2012, Make="Dodge", Model="Grand Caravan"},
                new Car{Year=2012, Make="Suzuki", Model="Kizashi"},
                new Car{Year=2012, Make="Suzuki", Model="Grand Vitara"},
                new Car{Year=2012, Make="Suzuki", Model="Equator"},
                new Car{Year=2012, Make="Suzuki", Model="SX4"},
                new Car{Year=2012, Make="Subaru", Model="Legacy"},
                new Car{Year=2012, Make="Subaru", Model="Impreza"},
                new Car{Year=2012, Make="Subaru", Model="Forester"},
                new Car{Year=2012, Make="Subaru", Model="Tribeca"},
                new Car{Year=2012, Make="Subaru", Model="Outback"},
                new Car{Year=2012, Make="Ferrari", Model="458 Italia"},
                new Car{Year=2012, Make="Ferrari", Model="FF"},
                new Car{Year=2012, Make="Smart", Model="Fortwo"},
                new Car{Year=2012, Make="Jaguar", Model="XF"},
                new Car{Year=2012, Make="Jaguar", Model="XK"},
                new Car{Year=2012, Make="Jaguar", Model="XJ"},
                new Car{Year=2012, Make="Jeep", Model="Wrangler"},
                new Car{Year=2012, Make="Jeep", Model="Compass"},
                new Car{Year=2012, Make="Jeep", Model="Grand Cherokee"},
                new Car{Year=2012, Make="Jeep", Model="Patriot"},
                new Car{Year=2012, Make="Jeep", Model="Liberty"},
                new Car{Year=2012, Make="Mazda", Model="Mazda5"},
                new Car{Year=2012, Make="Mazda", Model="Mazda2"},
                new Car{Year=2012, Make="Mazda", Model="CX-9"},
                new Car{Year=2012, Make="Mazda", Model="MX-5"},
                new Car{Year=2012, Make="Mazda", Model="Mazda6"},
                new Car{Year=2012, Make="Mazda", Model="Mazda3"},
                new Car{Year=2012, Make="Mazda", Model="Mazdaspeed 3"},
                new Car{Year=2012, Make="Mazda", Model="CX-7"},
                new Car{Year=2012, Make="Mazda", Model="Miata MX-5"},
                new Car{Year=2012, Make="Lamborghini", Model="Gallardo"},
                new Car{Year=2012, Make="Lamborghini", Model="Aventador"},
                new Car{Year=2012, Make="Tesla", Model="Model S"},
                new Car{Year=2012, Make="Tesla", Model="Roadster"},
                new Car{Year=2012, Make="Buick", Model="Verano"},
                new Car{Year=2012, Make="Buick", Model="LaCrosse"},
                new Car{Year=2012, Make="Buick", Model="Regal"},
                new Car{Year=2012, Make="Buick", Model="Enclave"},
                new Car{Year=2012, Make="Chrysler", Model="200"},
                new Car{Year=2012, Make="Chrysler", Model="300"},
                new Car{Year=2012, Make="Chrysler", Model="Town & Country"},
                new Car{Year=2012, Make="Kia", Model="Sportage"},
                new Car{Year=2012, Make="Kia", Model="Forte"},
                new Car{Year=2012, Make="Kia", Model="Optima"},
                new Car{Year=2012, Make="Kia", Model="Sedona"},
                new Car{Year=2012, Make="Kia", Model="Soul"},
                new Car{Year=2012, Make="Kia", Model="Sorento"},
                new Car{Year=2012, Make="Kia", Model="Rio"},
                new Car{Year=2012, Make="Lotus", Model="Exige"},
                new Car{Year=2012, Make="Lotus", Model="Evora"},
                new Car{Year=2012, Make="Bentley", Model="Continental GT"},
                new Car{Year=2012, Make="Bentley", Model="Mulsanne"},
                new Car{Year=2012, Make="Bentley", Model="Continental GTC"},
                new Car{Year=2012, Make="Bentley", Model="Continental Flying Spur"},
                new Car{Year=2012, Make="Bentley", Model="Continental Super"},
                new Car{Year=2012, Make="Bentley", Model="Continental"},
                new Car{Year=2012, Make="Mitsubishi", Model="Galant"},
                new Car{Year=2012, Make="Mitsubishi", Model="Eclipse"},
                new Car{Year=2012, Make="Mitsubishi", Model="Outlander"},
                new Car{Year=2012, Make="Mitsubishi", Model="i-MiEV"},
                new Car{Year=2012, Make="Mitsubishi", Model="Lancer"},
                new Car{Year=2012, Make="Mitsubishi", Model="Outlander Sport"},
                new Car{Year=2012, Make="Scion", Model="xB"},
                new Car{Year=2012, Make="Scion", Model="tC"},
                new Car{Year=2012, Make="Scion", Model="iQ"},
                new Car{Year=2012, Make="Scion", Model="xD"},
                new Car{Year=2012, Make="Rolls-Royce", Model="Ghost"},
                new Car{Year=2012, Make="Rolls-Royce", Model="Phantom"},
                new Car{Year=2012, Make="Maserati", Model="GranTurismo"},
                new Car{Year=2012, Make="Maserati", Model="Quattroporte"},
                new Car{Year=2012, Make="Maybach", Model="57"},
                new Car{Year=2012, Make="Maybach", Model="62"},
                new Car{Year=2012, Make="Maybach", Model="Landaulet"},
                new Car{Year=2012, Make="McLaren", Model="MP4-12C"},
                new Car{Year=2012, Make="Ram", Model="1500"},
                new Car{Year=2012, Make="Ram", Model="2500"},
                new Car{Year=2012, Make="Ram", Model="3500"},
                new Car{Year=2012, Make="Ram", Model="C/V"},
                new Car{Year=2013, Make="Ford", Model="Taurus"},
                new Car{Year=2013, Make="Ford", Model="C-MAX Hybrid"},
                new Car{Year=2013, Make="Ford", Model="Edge"},
                new Car{Year=2013, Make="Ford", Model="Escape"},
                new Car{Year=2013, Make="Ford", Model="Explorer"},
                new Car{Year=2013, Make="Ford", Model="Fiesta"},
                new Car{Year=2013, Make="Ford", Model="Flex"},
                new Car{Year=2013, Make="Ford", Model="Focus"},
                new Car{Year=2013, Make="Ford", Model="Focus ST"},
                new Car{Year=2013, Make="Ford", Model="Fusion"},
                new Car{Year=2013, Make="Ford", Model="Mustang"},
                new Car{Year=2013, Make="Ford", Model="Transit Connect"},
                new Car{Year=2013, Make="Hyundai", Model="Veloster"},
                new Car{Year=2013, Make="Hyundai", Model="Accent"},
                new Car{Year=2013, Make="Hyundai", Model="Elantra"},
                new Car{Year=2013, Make="Hyundai", Model="Equus"},
                new Car{Year=2013, Make="Hyundai", Model="Genesis Coupe"},
                new Car{Year=2013, Make="Hyundai", Model="Sonata"},
                new Car{Year=2013, Make="Chevrolet", Model="Cruze"},
                new Car{Year=2013, Make="Chevrolet", Model="Malibu"},
                new Car{Year=2013, Make="Chevrolet", Model="Tahoe"},
                new Car{Year=2013, Make="Audi", Model="S4"},
                new Car{Year=2013, Make="BMW", Model="X5"},
                new Car{Year=2013, Make="BMW", Model="X5 M"},
                new Car{Year=2013, Make="BMW", Model="X6"},
                new Car{Year=2013, Make="BMW", Model="X6 M"},
                new Car{Year=2013, Make="GMC", Model="Sierra 1500"},
                new Car{Year=2013, Make="GMC", Model="Yukon"},
                new Car{Year=2013, Make="GMC", Model="Yukon XL 1500"},
                new Car{Year=2013, Make="GMC", Model="Yukon XL 2500"},
                new Car{Year=2013, Make="Infiniti", Model="JX"},
                new Car{Year=2013, Make="Jaguar", Model="XK Series"},
                new Car{Year=2013, Make="Kia", Model="Rio"},
                new Car{Year=2013, Make="Kia", Model="Sorento"},
                new Car{Year=2013, Make="Lexus", Model="GS"},
                new Car{Year=2013, Make="Lexus", Model="LX"},
                new Car{Year=2013, Make="Lexus", Model="RX"},
                new Car{Year=2013, Make="Lincoln", Model="MKS"},
                new Car{Year=2013, Make="Lincoln", Model="MKT"},
                new Car{Year=2013, Make="Lincoln", Model="MKX"},
                new Car{Year=2013, Make="Mazda", Model="CX-5"},
                new Car{Year=2013, Make="Mazda", Model="MAZDA6"},
                new Car{Year=2013, Make="Nissan", Model="Altima"},
                new Car{Year=2013, Make="Nissan", Model="GT-R"},
                new Car{Year=2013, Make="Porsche", Model="911"},
                new Car{Year=2013, Make="Porsche", Model="Boxster"},
                new Car{Year=2013, Make="Porsche", Model="Cayenne"},
                new Car{Year=2013, Make="Porsche", Model="Panamera"},
                new Car{Year=2013, Make="Rolls-Royce", Model="Phantom"},
                new Car{Year=2013, Make="Scion", Model="FR-S"},
                new Car{Year=2013, Make="Scion", Model="tC"},
                new Car{Year=2013, Make="Subaru", Model="BRZ"},
                new Car{Year=2013, Make="Toyota", Model="Land Cruiser"},
                new Car{Year=2013, Make="Toyota", Model="Venza"},
                new Car{Year=2013, Make="Volkswagen", Model="CC"},
                new Car{Year=2013, Make="Volvo", Model="C30"},
                new Car{Year=2013, Make="Volvo", Model="C70"},
                new Car{Year=2013, Make="Volvo", Model="S60"},
                new Car{Year=2013, Make="Volvo", Model="XC90"},
                new Car{Year=2018, Make="Lexus", Model="RX Hybrid"},
                new Car{Year=2018, Make="Lexus", Model="IS"},
                new Car{Year=2018, Make="Lexus", Model="GX"},
                new Car{Year=2018, Make="Lexus", Model="LS Hybrid"},
                new Car{Year=2018, Make="Lexus", Model="GS"},
                new Car{Year=2018, Make="Lexus", Model="LS"},
                new Car{Year=2018, Make="Lexus", Model="IS-F"},
                new Car{Year=2018, Make="Lexus", Model="CT"},
                new Car{Year=2018, Make="Lexus", Model="RX"},
                new Car{Year=2018, Make="Lexus", Model="HS"},
                new Car{Year=2018, Make="Lexus", Model="LX"},
                new Car{Year=2018, Make="Lexus", Model="ES"},
                new Car{Year=2018, Make="Lexus", Model="IS F"}
            };

            cars.ForEach(x => context.Cars.Add(x));
            context.SaveChanges();
        }
    }
}
